### ISSUE TITLE
doubt: shared webhost

### ISSUE THREAD

**Issue by AmidoNI2** [dataunlocker/save-analytics-from-content-blockers#20]
is there any way that we can run the setup on a shared webhost that the most '' advanced '' access is PHP / SQL / ???

I have a serious adblock problem holding our statistics, we use customized Wordpress by ourselves, but we have this limitation of the webhost

**Comment by ZitRos** [comment]
Hello! Thanks for asking. There should be a way:

1. If you can control DNS of your website (can you add CNAME records?), the answer is [dataunlocker.com](https://dataunlocker.com) (launching soon - leave your email there to be notified). No server is needed for it, all config is purely client-side (and DNS).
2. If you can't control DNS, but you can write PHP scripts, you can write an endpoint which can proxy the traffic to f.e. [dataunlocker.com](https://dataunlocker.com) (when it launches, we also support "proxy behind proxy") or your own proxy (the [container](https://hub.docker.com/r/zitros/analytics-saviour) from this repository).

Let me know what is your situation so I can give a more granular advice. Thanks!

**Comment by ZitRos** [comment]
@AmidoNI2 ping: does this answer your question?

**Comment by ZitRos** [comment]
Closed due to inactivity. Also, [dataunlocker.com](https://dataunlocker.com) is now available to public, check it out!
