### ISSUE TITLE
Change cache headers to public?

### ISSUE THREAD

**Issue by ronenteva** [dataunlocker/save-analytics-from-content-blockers#24]
Files like `www.googletagmanager.com/gtag/js` return `cache-control: private, max-age=900`.

I suggest modifying it to `public` as it should be safe and will save a lot of load on the servers, what do you think?

**Comment by ZitRos** [comment]
Hmm, sounds interesting. I guess if GTM sets this header explicitly to private, perhaps, there is a reason for it? Caching can be harmful for some use-cases we don't know.

**Comment by ronenteva** [comment]
Yes, after thinking about it more I tend to agree, better not risk it.

Sorry for the trouble :)
