### ISSUE TITLE
IP override for Google Analytics 4 

### ISSUE THREAD

**Issue by ronenteva** [dataunlocker/save-analytics-from-content-blockers#25]
The IP override works fine on Google Analytics but not on GA4.
All hits are shown from the server IP.

**Comment by ZitRos** [comment]
Hello! That’s because Google’s measurement protocol v2 does not yet support
&uip URL parameter. However, with some magic applied, location override
already works in dataunlocker.com for GA4 as well.

**Comment by ronenteva** [comment]
Can't this magic be a open-sourced? Or is that a selling point for the paid version?

**Comment by ZitRos** [comment]
Not a selling point. I feel uncomfortable open-sourcing things which **will** change just tomorrow (read: which are in alpha) and which will be removed from the API completely at some point. Within DataUnlocker, we just can afford experimenting, as once it changes there will be an immediate fix from our side.

The [latest Measurement Protocol spec](https://developers.google.com/analytics/devguides/collection/protocol/ga4) should very soon transition to beta with `uip` parameter supported. Please wait and take it as "there is no way to do it before MPv2 goes beta". That's Google's problem that they push GAv2 to their customers before updating the protocol at the end of the day :P

P.S. DataUnlocker isn't the paid version of this open sourced app/container; it uses a principally different and a better approach to proxy "everything", without any common code.

**Comment by ronenteva** [comment]
Got it, that makes sense. 
Thanks for explaining!

**Comment by julesGoullee** [comment]
Regarding this issue, I understand your comments, @ZitRos, how https://developers.google.com/tag-manager/serverside manage to accomplish this task then?

**Comment by ZitRos** [comment]
In fact, I've never tried Google's server-side tagging solution. From [here](https://developers.google.com/tag-manager/serverside/send-data#update_the_gtmjs_source_domain) I can see that it doesn't solve the ad blocking problem (replacing the domain isn't enough).

To answer your question, @julesGoullee, did you try server-side GTM with GA4? Does it work with locations?

**Comment by julesGoullee** [comment]
I didn't try it too. I thought the purpose of this is to bypass [adblocker](https://developers.google.com/tag-manager/serverside/intro) following the explanation schema. Do you have any private info about when the new GA4 will support `uip` params ? Seems this issue is open for months, I guess the GA4 homepage show `alpha` for months as well

**Comment by ZitRos** [comment]
I can't share the release dates nor any other related info (obviously because of the company's policies and the common sense).

Though to answer the original question of this issue, I think it is [no secret now](https://cling.com/c/Today_I_Learned_Random_Tech_St-b3YIeyHr6mjzmIght5flVfD) that Google tends to prefix alpha/beta URL parameters with underscore `_`, so does `&_uip=x.x.x.x` work well for Google Analytics 4. I am pretty sure server-side GTM uses it as well if it works with GA4.

I would hold from updating the code of this [open-sourced container](https://hub.docker.com/r/zitros/analytics-saviour) with `_uip`, however, given that the new protocol release already takes months we can do it I think. Does it sound good?

**Comment by julesGoullee** [comment]
Wow. Didn't know it before, was a secret at least for me! I've tried it out, works perfectly! I can make a pr for this repo, definitely not a big deal to prefix the parameter, I guess everyone will appreciate having it right now when it goes officially released reverting these changes should be smooth IMO.
Thx for your help

**Comment by ZitRos** [comment]
Yes please go ahead and contribute! I wish I have added some very basic tests to this repo when I started it (I test it manually) but this should be a very straightforward fix.

**Comment by julesGoullee** [comment]
Let's go! [https://github.com/dataunlocker/save-analytics-from-content-blockers/pull/28](https://github.com/dataunlocker/save-analytics-from-content-blockers/pull/28)

**Comment by ZitRos** [comment]
This is now [deployed](https://hub.docker.com/r/zitros/analytics-saviour/tags?page=1&ordering=name). @julesGoullee are you using the container? Please confirm it works, I didn't run it.

**Comment by julesGoullee** [comment]
I started with the container, work perfectly then I faced issues, I went to deployment from source, I think now I will consider moving back to the container bundle

**Comment by ZitRos** [comment]
Let me know how it goes - I'll keep the issue open for now.

**Comment by ZitRos** [comment]
I assume it's verified now. Thanks!

**Comment by julesGoullee** [comment]
The changes work well, the container I didn't test it yet. I will contact you later if I have any issue with the container

**Comment by ZitRos** [comment]
Thanks!

**Comment by wilsonpage** [comment]
Can someone confirm if `_uip` is still working?

**Comment by ZitRos** [comment]
Hi @wilsonpage! You should be able to confirm it easily by making a hit. Then, in GA realtime panel you'll see the location corresponding to that IP.

**Comment by wilsonpage** [comment]
> Hi @wilsonpage! You should be able to confirm it easily by making a hit. Then, in GA realtime panel you'll see the location corresponding to that IP.

Ah, it's working for me now! I was trying to use the official GA4 Measurement Protocol, but the API seems half-baked and doesn't have all the options the unofficial/private API (used in `gtag.js`) has.

**Comment by iammattmartin** [comment]
Could you document it?

**Comment by wilsonpage** [comment]
@iammattmartin this is my test script I was using:

```ts
/* eslint-disable no-console */
import fetch from 'node-fetch';

(async () => {
  const url = new URL('https://google-analytics.com/g/collect?v=2');

  url.searchParams.set('tid', 'G-BLVBF7CC76');
  // url.searchParams.set('gtm', '2oe6t0');
  url.searchParams.set('_z', 'ccd.v9B');

  // client id
  url.searchParams.set('cid', '1656610788');

  // session id
  url.searchParams.set('sid', '1656610180');

  // user language
  url.searchParams.set('ul', 'en-gb');

  // screen resolution
  url.searchParams.set('sr', '1440x900');

  //
  url.searchParams.set('_s', '1');

  // Count of sessions recorded by GA4. This value increases by one each time a new session is detected ( when the session expires )
  url.searchParams.set('sct', '1');

  // session engagement
  url.searchParams.set('seg', '1');

  // document location
  url.searchParams.set('dl', 'https://example.com/3');

  // document referrer
  url.searchParams.set('dr', 'https://google.com/');

  // document title
  url.searchParams.set('dt', 'Example title');

  // event name
  url.searchParams.set('en', 'page_view');

  // ?
  url.searchParams.set('_nsi', '1');

  // user id (determines location)
  url.searchParams.set('uip', '31.29.124.235');
  url.searchParams.set('_uip', '31.29.124.235');

  // event parameters
  url.searchParams.set('epn.artistId', '123');

  // ?
  url.searchParams.set('_ee', '1');

  // first_view
  // url.searchParams.set('_fv', '1');

  // session_start
  // url.searchParams.set('_ss', '1');

  console.log(url);
  // console.log(
  //   'https://google-analytics.com/g/collect?v=2&tid=G-QS6H9Y8HYR&gtm=2oe6t0&_z=ccd.v9B&cid=1656610787&ul=en-gb&sr=1440x900&_s=1&sid=1656610180&sct=1&seg=1&dl=https%3A%2F%2Fsongwhip.com%2Fbat&dr=https%3A%2F%2Fsongwhip.com%2F&dt=Songwhip%20Bat&en=page_view&_nsi=1&_uip=69.162.81.155&_ee=1'
  // );

  // console.log(url.toString());

  const res = await fetch(url.toString(), {
    method: 'POST',
    headers: {
      Accept: '*/*',
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
      'Sec-Ch-Ua-Mobile': '?0',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'no-cors',
      'Sec-Fetch-Site': 'cross-site',
      'User-Agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
    },
  });

  console.log(res.status);
})();
```

**Comment by wilsonpage** [comment]
This cheatsheet is also handy:
https://www.thyngster.com/ga4-measurement-protocol-cheatsheet/

**Comment by iammattmartin** [comment]
Thanks but in terms of integration within this specific project. Did you make changes to the .js? Would be good if you could submit  or fork it so people can use :)

**Comment by iammattmartin** [comment]
Ah ok, thanks.

**Comment by ThiloReintjes** [comment]
I'm making requests to `www.google-analytics.com/mp/collect` with the following parameters:

Query:
- `_uip`
- `uip`

Header:
- `X-Forwarded-For`
- `User-Agent`

Body:
- `user_id` (unique for each user, custom value)

Despite these details, Google Analytics is only recording hits from my server as a single user. 
I made sure that all IP values are the IP of the user.
I'm using the same value for `client_id` as I am for `user_id`. 

Is there a step or setting I'm overlooking?

**Comment by nikitaeverywhere** [comment]
@ThiloReintjes IP overrides work at least for `/g/collect` endpoint (it follows almost the same spec as `/mp/collect`). I doubt that `/mp/collect` specifically supports IP overrides, as even [this issue](https://issuetracker.google.com/issues/179160710) is P4.
