### ISSUE TITLE
user-agent not forwarded

### ISSUE THREAD

**Issue by julesGoullee** [dataunlocker/save-analytics-from-content-blockers#27]
With user agent forwarded, ga will show up browser and operating system details

**Comment by ZitRos** [comment]
Hello Jules! This open-sourced solution and DataUnlocker forwards all original headers to the proxy server, including User-Agent. Please open a new issue with more specific information if needed. Thanks!

**Comment by julesGoullee** [comment]
If it's already pass then it's fine but, from my experience doesn't show up properly in google analytics. I've manually copy user-agent headers here, https://github.com/dataunlocker/save-analytics-from-content-blockers/blob/master/src/modules/proxy.js#L53, then it works, I recommend you to double-check this

**Comment by ZitRos** [comment]
Tested: I proxied headers to the "echo" back end via this container. I doubt all headers are proxied, here's the response of the echo back end:

```json
{
  "method": "GET",
  "url": "/health-check",
  "headers": {
    "host": "localhost/*(ZXh5MzlvNWJzb2hoLm5pa2l0YS50aw)*",
    "x-request-id": "59a0a061b221ec6b26eec4b48536721b",
    "x-real-ip": "192.168.1.1",
    "x-forwarded-for": "192.168.1.1",
    "x-forwarded-host": "localhost/*(ZXh5MzlvNWJzb2hoLm5pa2l0YS50aw)*",
    "x-forwarded-port": "443",
    "x-forwarded-proto": "https",
    "x-scheme": "https",
    "content-length": "0",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
    "sec-ch-ua-mobile": "?0",
    "dnt": "1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "identity",
    "accept-language": "en,en-US;q=0.9,ru;q=0.8,uk;q=0.7",
    "accept-charset": "utf-8"
  },
  "body": ""
}
```

You can clearly see 

```
 "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
```

Maybe, it's the problem with your setup?

**Comment by julesGoullee** [comment]
Ok thx, I will double check

**Comment by julesGoullee** [comment]
I suppose my issue was due to the delay of 24h in ga dashboard to show up data, thx for the help

**Comment by ZitRos** [comment]
Some people like @vitobotta complained about things not visible in GA dashboard as well :) This also not an issue with [DataUnlocker](https://dataunlocker.com/). It's Google Analytic's realtime view isn't very reliable, but everything is taken into account in a while (some data is available immediately, and something can take up to 1 day to sync). I feel like I should document it [somewhere](https://dataunlocker.com/docs/measuring-impact/google-analytics/).

Closing this issue for now, thanks for confirming.
