### ISSUE TITLE
/ga-audiences

### ISSUE THREAD

**Issue by iammattmartin** [dataunlocker/save-analytics-from-content-blockers#30]
It appears when Signals data is turned on, the browser makes a call to a google page for /ga-audiences.

This does not appear mapped so some browsers will try and connect to a Google server. 

In our instanace the URL in the javascript seems half encoded but half not.

`https://www.%/*(YWRz)*/ga-audiences`

**Comment by ZitRos** [comment]
Needs to be investigated. Most likely the back end makes an invalid replacement in the proxied script's source code. PRs are welcome!

**Comment by iammattmartin** [comment]
The part of the gtag/js is:

```
var Ty=function(a,b,c,d){var e=a+"?"+b;Qy&&(d=!(0===e.indexOf("https://www.google-analytics.com/g/collect")||0===e.indexOf("https://analytics.google.com/g/collect")));Ry&&d&&!Kx?Py(e,c):Sy(a,b,c)},Uy=function(a){return a&&0===a.indexOf("google.")&&"google.com"!=a?"https://www.%/ads/ga-audiences?v=1&t=sr&slf_rd=1&_r=4&".replace("%",a):void 0},Ry=!1;Ry=!0;var Qy=!1;var Vy=function(){this.C=1;this.F={};this.g=new Sf;this.o=-1};Vy.prototype.s=function(a,b){var c=this,d;try{d=new Ly(a,this.F,b)}catch(n){a.abort()}var e=Mx(a);e&&this.g.C(d)||this.flush();if(e&&this.g.add(d)){if(0>this.o){var f=A,g=f.setTimeout,h;a.Ua()?Wy?(Wy=!1,h=Xy):h=Yy:h=5E3;this.o=g.call(f,function(){return c.flush()},h)}}else{var l=Uf(d,this.C++);Ty(d.o,l.rf,l.body,d.C);Zy(d,a.Ee,a.ob,String(a.Db(R.jd,a.B(R.jd))))}};
```

It seems they're using a % in place of which domain they would expect to see.

In our instance, as above. it changes to `https://www.%/*(YWRz)*/ga-audiences`
