### ISSUE TITLE
GA Changes on 17th Feb

### ISSUE THREAD

**Issue by iammattmartin** [dataunlocker/save-analytics-from-content-blockers#33]
It looks like GA made some changes to the JS on 17th Feb and this script in the current form no longer works.

It alters one GA with an incomplete record and makes it unusable so maybe worth considering for anyone yet to roll out.

**Comment by ZitRos** [comment]
Hello! Thank you for reporting this.

> It alters one GA with an incomplete record and makes it unusable so maybe worth considering for anyone yet to roll out.

Do you know exactly what piece of code in that JavaScript stopped from being replaced? Any fix in mind? I'm a bit busy nowadays and will be really glad if you could debug & PR for instance.

**Comment by iammattmartin** [comment]
Line 330 seems to be the offending one.

```
var KA={};var LA={};LA[S.cg]="cc";LA[S.dg]="ci";LA[S.eg]="cm";LA[S.fg]="cn";LA[S.gg]="cs";LA[S.hg]="ck";var BA=function(){var a="www";HA&&GA&&(a=GA);return"https://"+a+".google-analytics.com/*(Zw)*/*(Y29sbGVjdA)*"},AA=function(){var a;HA&&GA&&(a=GA);return"https://"+(a?a+".":"")+"mydomain.com/xxx/*(YW5hbHl0aWNzLmdvb2dsZS5jb20)*/*(Zw)*/*(Y29sbGVjdA)*"},
```

No fix but then again, i've not really been able to check much in to this.

**Comment by iammattmartin** [comment]
It appears this instance of google-analytics.com in the code needs a specialContentReplace due to the prefix it uses of `https://"+a+".`.

**Comment by ZitRos** [comment]
Can anyone suggest and test a fix please? I have no time to do it right now :(

**Comment by VityaSchel** [comment]
> Line 330 seems to be the offending one.
> 
> ```
> var KA={};var LA={};LA[S.cg]="cc";LA[S.dg]="ci";LA[S.eg]="cm";LA[S.fg]="cn";LA[S.gg]="cs";LA[S.hg]="ck";var BA=function(){var a="www";HA&&GA&&(a=GA);return"https://"+a+".google-analytics.com/*(Zw)*/*(Y29sbGVjdA)*"},AA=function(){var a;HA&&GA&&(a=GA);return"https://"+(a?a+".":"")+"mydomain.com/xxx/*(YW5hbHl0aWNzLmdvb2dsZS5jb20)*/*(Zw)*/*(Y29sbGVjdA)*"},
> ```
> 
> The original line of which:
> 
> ```
> var KA={};var LA={};LA[S.cg]="cc";LA[S.dg]="ci";LA[S.eg]="cm";LA[S.fg]="cn";LA[S.gg]="cs";LA[S.hg]="ck";var BA=function(){var a="www";HA&&GA&&(a=GA);return"https://"+a+".google-analytics.com/g/collect"},AA=function(){var a;HA&&GA&&(a=GA);return"https://"+(a?a+".":"")+"analytics.google.com/g/collect"},
> ```
> 
> No fix but then again, i've not really been able to check much in to this.

So we should replace this line and it will work again?

**Comment by iammattmartin** [comment]
Not so much replacing the line, but the re-writing is not working so until that matching is fixed, it won't work.

**Comment by ZitRos** [comment]
This backend basically is capable of finding and replacing something in the script content via regexp. If you can find what to replace or fix, you can add a rule [here](https://github.com/dataunlocker/save-analytics-from-content-blockers/blob/494e0233c08e093cf3a51575c6b992f454f8d651/config.js#L66) (for extra cases), or add a path masking [here](https://github.com/dataunlocker/save-analytics-from-content-blockers/blob/494e0233c08e093cf3a51575c6b992f454f8d651/config.js#L90), which applies to all scripts. Probably, you can remove path masking if it conflicts and replaces it with a "specialContentReplace" rule.

**Comment by iammattmartin** [comment]
Nothing i've tried works so we've switched to using nginx as a proxy. Although a loss of user demographics, at least we have some stats now.

**Comment by ZitRos** [comment]
@iammattmartin is there anything preventing you from using dataunlocker.com?

**Comment by iammattmartin** [comment]
Mainly our pref is keep things like this in-house so we're not reliant on a third party service being up.

**Comment by VityaSchel** [comment]
Can someone explain what to do so I can write a fix and make PR? This issue is 1month+ old and there is no statistics for this period

**Comment by ZitRos** [comment]
> Can someone explain what to do so I can write a fix and make PR? This issue is 1month+ old and there is no statistics for this period

1. Find a problem and how to fix it by changing the code
2. Fix it & submit PR
3. In PR description, note how to test the fix (since there are no automated test coverage)

I will be happy to review it. Thanks!

**Comment by iammattmartin** [comment]
@VityaSchel we've started to use https://github.com/fr0der1c/google-analytics-proxy. Geo data does not come through but at least we have stats.

**Comment by sneko** [comment]
@iammattmartin do you know why Geo data does not go through the mentioned proxy? Did you find something better in the meantime?

**Comment by iammattmartin** [comment]
It isn't and does work but requires a bit more work than in the scope of this project.

I've had mine working with uip and GA4 for a few months now.

**Comment by iammattmartin** [comment]
It does work but I don't have time to submit a PR and doc the change.
<img width="663" alt="Screenshot 2022-08-18 at 02 20 59" src="https://user-images.githubusercontent.com/15971590/185271273-be15ed3b-a342-4c01-ac39-3196a247f049.png">

**Comment by iammattmartin** [comment]
When it was using stock code, it was only showing the UK. After our changes, it now shows other countries.

The stats are correct though, this is a specific site for UK audience and matches our matomo stats.

**Comment by iammattmartin** [comment]
Thanks but this is going off topic entirely and as I am not longer affected by this I am closing it as the repo owner isn't going to fix from the past convo.

**Comment by ZitRos** [comment]
@iammattmartin hey! PRs are welcome! It should be actually the one-liner PR adding a parameter here: https://github.com/dataunlocker/save-analytics-from-content-blockers/blob/494e0233c08e093cf3a51575c6b992f454f8d651/config.js#L83

**Comment by iammattmartin** [comment]
Sorry thats what I mean, this issue wasn't about that and got taken over by others adding stuff unrelated.

This issue was about the proxy breaking for what was reported at the start of the issue.

**Comment by ZitRos** [comment]
Got it. Do you have any fix in mind?

**Comment by VityaSchel** [comment]
lmao this issue is looped basically needs one simple pr but no one wants to do it

**Comment by iammattmartin** [comment]
It's not a case that no one wants to do it, some have tried but it doesn't work. Given you yourself said no one wants to do it but then asked what to do, seems pretty rich claiming no one wants to do it.
