### ISSUE TITLE
How to use Dataunlocker in nextjs13?

### ISSUE THREAD

**Issue by TonsiTT** [dataunlocker/save-analytics-from-content-blockers#37]
I tried adding the script as a client component and importing it into the layout file, and it doesn't seem to be working. On the dashboard, I can see the count api.dataunlocker.com increasing but that's it. google analytics or tag manager arent being proxied. 

On the other hand if I inject the script via tampermonkey on the same site it seems to be working normally.

Confused on what to do

**Comment by nikitaeverywhere** [comment]
Hello! Please contact support@dataunlocker.com mentioning your website, we'll take a look. Thanks for asking!
